project_id = "hvhfxcwazrpfboetzkve"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.dev"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
secure_password_change_enabled = true
enable_manual_linking = false

[realtime]
enabled = true
port = 54323

[storage]
enabled = true
port = 54324
file_size_limit = "50MiB"
image_transformation = {enabled = true}

[functions.analyze-document]
verify_jwt = false

[functions.process-feedback]
verify_jwt = false

[edge_runtime]
enabled = true
port = 54326