// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hvhfxcwazrpfboetzkve.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2aGZ4Y3dhenJwZmJvZXR6a3ZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2OTMwODksImV4cCI6MjA2OTI2OTA4OX0.ckxXYelSrkRfAmJxOT4huUgDJyeQYr4-cUre1ucPN64";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});